= Vert.x MQTT client

== Using Vert.x MQTT client
== Getting started

=== Connect/Disconnect
The client gives you opportunity to connect to a server and disconnect from it.

Also, you could specify things like the host and port of a server you would like
to connect to passing instance of `link:../../apidocs/io/vertx/mqtt/MqttClientOptions.html[MqttClientOptions]` as a param through constructor.

This example shows how you could connect to a server and disconnect from it using Vert.x MQTT client and calling `link:../../apidocs/io/vertx/mqtt/MqttClient.html#connect--[connect]` and `link:../../apidocs/io/vertx/mqtt/MqttClient.html#disconnect--[disconnect]` methods.
[source,java]
----
MqttClientOptions options = new MqttClientOptions()
  .setHost("iot.eclipse.org")
  .setPort(1883);

MqttClient client = new MqttClientImpl(vertx, options);

client.connect(s -> client.disconnect());
----
NOTE: default address of server provided by `link:../../apidocs/io/vertx/mqtt/MqttClientOptions.html[MqttClientOptions]` is localhost:1883 and localhost:8883 if you are using SSL/TSL.
=== Subscribe to a topic

Now, lest go deeper and take look at this example:

[source,java]
----
client.publishHandler(s -> {
  System.out.println("There are new message in topic: " + s.topicName());
  System.out.println("Content(as string) of the message: " + s.payload().toString());
  System.out.println("QoS: " + s.qosLevel());
})
  .subscribe("rpi2/temp", 2);
----

Here we have the example of usage of `link:../../apidocs/io/vertx/mqtt/MqttClient.html#subscribe-java.lang.String-int-[subscribe]` method. In order to receive messages from rpi2/temp topic we call `link:../../apidocs/io/vertx/mqtt/MqttClient.html#subscribe-java.lang.String-int-[subscribe]` method.
Although, to handle received messages from server you need to provide a handler, which will be called each time you have a new messages in the topics you subscribe on.
As this example shows, handler could be provided via `link:../../apidocs/io/vertx/mqtt/MqttClient.html#publishHandler-io.vertx.core.Handler-[publishHandler]` method.

=== Publishing message to a topic

If you would like to publish some message into topic then `link:../../apidocs/io/vertx/mqtt/MqttClient.html#publish-java.lang.String-io.vertx.core.buffer.Buffer-io.netty.handler.codec.mqtt.MqttQoS-boolean-boolean-[publish]` should be called.
Let's take a look at the example:
[source,java]
----
client.publish("temperature",
  Buffer.buffer("hello".getBytes()),
  MqttQoS.AT_LEAST_ONCE,
  false,
  false);
----

In the example we send message to topic with name "temperature".